name: Deploy Flask App to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy project to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          rsync -avz \
            --exclude '.git' \
            --exclude '__pycache__' \
            -e "ssh -o StrictHostKeyChecking=no -i key.pem -p ${{ secrets.SSH_PORT }}" \
            ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/zipfarm-flask-app

      - name: SSH and deploy Docker container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem -p ${{ secrets.SSH_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'bash -s' << EOF
            cd /home/${{ secrets.EC2_USERNAME }}/zipfarm-flask-app

            docker stop zipfarm-app || true
            docker rm zipfarm-app || true

            docker build -t zipfarm-app .
            docker run -d -p 6000:6000 --name zipfarm-app zipfarm-app
          EOF